document.writeln("<!--底部导航-->");
document.writeln("		<div class=\'down\'>");
document.writeln("			<!--五个红标标-->");
document.writeln("			<div class=\'down-list\'>");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<div class=\'down-list-tb\'>");
document.writeln("							<a>正</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'down-list-text\'>");
document.writeln("							<p>正品保障</p>");
document.writeln("							<span>100%正品商场</span>");
document.writeln("						</div>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<div class=\'down-list-tb\'>");
document.writeln("							<a>税</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'down-list-text\'>");
document.writeln("							<p>税费</p>");
document.writeln("							<span>100%税务透明</span>");
document.writeln("						</div>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<div class=\'down-list-tb\'>");
document.writeln("							<a>价</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'down-list-text\'>");
document.writeln("							<p>价格</p>");
document.writeln("							<span>价格适中</span>");
document.writeln("						</div>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<div class=\'down-list-tb\'>");
document.writeln("							<a>物</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'down-list-text\'>");
document.writeln("							<p>物流</p>");
document.writeln("							<span>物流便捷</span>");
document.writeln("						</div>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<div class=\'down-list-tb\'>");
document.writeln("							<a>售</a>");
document.writeln("						</div>");
document.writeln("						<div class=\'down-list-text\'>");
document.writeln("							<p>售后</p>");
document.writeln("							<span>保证交易安全</span>");
document.writeln("						</div>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("");
document.writeln("			<!--底部中间-->");
document.writeln("			<div class=\'down-center\'>");
document.writeln("");
document.writeln("				<div class=\'gwzl\'>");
document.writeln("					<table cellspacing=\'0\' cellpadding=\'0\'>");
document.writeln("						<tr>");
document.writeln("							<th>购物指南</th>");
document.writeln("							<th>付款及退款</th>");
document.writeln("							<th>配送方式及费用</th>");
document.writeln("							<th>购物风险保障</th>");
document.writeln("							<th>常见问题</th>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td><a href='helpCenter.html'>购物流程</a></td>");
document.writeln("							<td>付款方式</td>");
document.writeln("							<td>快递与物流说明及费用</td>");
document.writeln("							<td>六大优势</td>");
document.writeln("							<td>常见问题汇总</td>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td>发票制度</td>");
document.writeln("							<td>货到付款</td>");
document.writeln("							<td>EMS特慢邮寄</td>");
document.writeln("							<td>15无条件退货</td>");
document.writeln("							<td>投诉与监督</td>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td>购物流程</td>");
document.writeln("							<td>积分规则</td>");
document.writeln("							<td>货到付款配送及费用</td>");
document.writeln("							<td>支持全国货到付款</td>");
document.writeln("							<td>微信分享即可赚取佣金说明</td>");
document.writeln("						</tr>");
document.writeln("					</table>");
document.writeln("				</div>");
document.writeln("");
document.writeln("				<div class=\'phone\'>");
document.writeln("					<p>800-8820</p>");
document.writeln("					<span>一个打不通的电话</span>");
document.writeln("				</div>");
document.writeln("");
document.writeln("			</div>");
document.writeln("");
document.writeln("			<!--最底部-->");
document.writeln("			<div class=\'down-down\'>");
document.writeln("				<a>版权所有：有个锤子版权</a>");
document.writeln("			</div>");
document.writeln("");
document.writeln("		</div>");