document.writeln("<!--顶部-->");
document.writeln("		<div class=\'top\' id=\'top\'>");
document.writeln("			<div class=\'h\'>");
document.writeln("				<div class=\'left\'>");
document.writeln("					<a href=\'index.html\'>主页</a>");
document.writeln("					<span>|</span>");
document.writeln("					<a href='页面索引.html'>导航</a>");
document.writeln("				</div>");
document.writeln("				<div class=\'right\'>");
document.writeln("					<a href=\'SignMain.html\'>登录</a>");
document.writeln("					<span>|</span>");
document.writeln("					<a href=\'registerMain.html\'>注册</a>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("");
document.writeln("		<!--搜索栏-->");
document.writeln("		<div class=\'S\' id=\'body-top\'>");
document.writeln("			<div class=\'s\'>");
document.writeln("				<div class=\'roglogo\'>");
document.writeln("					<img src=\'img/logo.png\' style=\'width: 208px; height: 116px;\' />");
document.writeln("				</div>");
document.writeln("				<div class=\'search\'>");
document.writeln("					<div class=\'search-top\'>");
document.writeln("						<input type=\'text\' placeholder=\'请输入商品关键字\' />");
document.writeln("						<button class=\'ss\'>");
document.writeln("								<a>搜索</a>");
document.writeln("							</button>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'search-recommend\'>");
document.writeln("					<a>显示屏</a>");
document.writeln("					<span>|</span>");
document.writeln("					<a>显卡</a>");
document.writeln("					<span>|</span>");
document.writeln("					<a>CPU</a>");
document.writeln("					<span>|</span>");
document.writeln("					<a>内存条</a>");
document.writeln("					<span>|</span>");
document.writeln("					<a>主板</a>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		<!--导航栏-->");
document.writeln("		<nav class=\'main-nav\'>");
document.writeln("			<div class=\'content\'>");
document.writeln("				<div class=\'classify\'>");
document.writeln("					<div class=\'tb\'></div>");
document.writeln("					<div class=\'fl\'>");
document.writeln("						<a>分类</a>");
document.writeln("					</div>");
document.writeln("");
document.writeln("				</div>");
document.writeln("				<ul class=\'list\'>");
document.writeln("					<li>");
document.writeln("						<a>首页</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a href='IntegralMall.html'>积分商城</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a>团购</a>");
document.writeln("					</li>");
document.writeln("					<li>");
document.writeln("						<a>秒杀</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</div>");
document.writeln("		</nav>");